//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.629.0 using the following command:
// xscgen -n =Ariane.SaveFile.Contract ../tmlu.xsd
namespace Ariane.SaveFile.Contract
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("style", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Style
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<float> _dashArray;
        
        [System.Xml.Serialization.XmlElementAttribute("dashArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<float> DashArray
        {
            get
            {
                return this._dashArray;
            }
            private set
            {
                this._dashArray = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DashArray collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DashArraySpecified
        {
            get
            {
                return (this.DashArray.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Style" /> class.</para>
        /// </summary>
        public Style()
        {
            this._dashArray = new System.Collections.ObjectModel.Collection<float>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dashScale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float DashScale { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("fillColorString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FillColorString { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lineType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StyleLineType LineType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lineTypeScale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float LineTypeScale { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("opacity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Opacity { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sizeMode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StyleSizeMode SizeMode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("strokeColorString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StrokeColorString { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("strokeThickness", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float StrokeThickness { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StyleLineType", Namespace="", AnonymousType=true)]
    public enum StyleLineType
    {
        
        STANDARD,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StyleSizeMode", Namespace="", AnonymousType=true)]
    public enum StyleSizeMode
    {
        
        SWITCHABLE,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("layer", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Layer
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("constant", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Constant { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("locked", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Locked { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("style", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Style Style { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("visible", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Visible { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("corner", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Corner
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("editable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Editable { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("layer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Layer Layer { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CornerType Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ZOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZOrder { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("positionX", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double PositionX { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("positionY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double PositionY { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CornerType", Namespace="", AnonymousType=true)]
    public enum CornerType
    {
        
        NONE,
        
        GRIP,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFile", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CaveFile", Namespace="")]
    public partial class CaveFile
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("caveName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CaveName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("firstStartAbsoluteElevation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float FirstStartAbsoluteElevation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("geoCoding", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeoCoding { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CaveFileListAnnotationAnnotation> _listAnnotation;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("ListAnnotation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Annotation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CaveFileListAnnotationAnnotation> ListAnnotation
        {
            get
            {
                return this._listAnnotation;
            }
            private set
            {
                this._listAnnotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CaveFile" /> class.</para>
        /// </summary>
        public CaveFile()
        {
            this._listAnnotation = new System.Collections.ObjectModel.Collection<CaveFileListAnnotationAnnotation>();
            this._data = new System.Collections.ObjectModel.Collection<CaveFileDataSRVD>();
            this._layers = new System.Collections.ObjectModel.Collection<Layer>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CaveFileDataSRVD> _data;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("Data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SRVD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CaveFileDataSRVD> Data
        {
            get
            {
                return this._data;
            }
            private set
            {
                this._data = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileUnit Unit { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("useMagneticAzimuth", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool UseMagneticAzimuth { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Constraints", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Constraints { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CartoLine { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoPage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileCartoPage CartoPage { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoRectangle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CartoRectangle { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoSelection", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CartoSelection { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoEllipse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CartoEllipse { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoSpline", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CartoSpline { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Layer> _layers;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("Layers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("layerList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Layer> Layers
        {
            get
            {
                return this._layers;
            }
            private set
            {
                this._layers = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoOverlay", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CartoOverlay { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CartoLinkedSurface", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object CartoLinkedSurface { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileListAnnotation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileListAnnotation
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CaveFileListAnnotationAnnotation> _annotation;
        
        [System.Xml.Serialization.XmlElementAttribute("Annotation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CaveFileListAnnotationAnnotation> Annotation
        {
            get
            {
                return this._annotation;
            }
            private set
            {
                this._annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CaveFileListAnnotation" /> class.</para>
        /// </summary>
        public CaveFileListAnnotation()
        {
            this._annotation = new System.Collections.ObjectModel.Collection<CaveFileListAnnotationAnnotation>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileListAnnotationAnnotation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileListAnnotationAnnotation
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("attachStationA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AttachStationA { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("attachStationB", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AttachStationB { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("attachedDensityGraph", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object AttachedDensityGraph { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("fromAction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileListAnnotationAnnotationFromAction FromAction { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileListAnnotationAnnotationType Type { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileListAnnotationAnnotationFromAction", Namespace="", AnonymousType=true)]
    public enum CaveFileListAnnotationAnnotationFromAction
    {
        
        Distance,
        
        [System.Xml.Serialization.XmlEnumAttribute("Swim Distance")]
        Swim_Distance,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileListAnnotationAnnotationType", Namespace="", AnonymousType=true)]
    public enum CaveFileListAnnotationAnnotationType
    {
        
        LINKEDTOTWOSTATION,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileData", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileData
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CaveFileDataSRVD> _sRVD;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("SRVD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CaveFileDataSRVD> SRVD
        {
            get
            {
                return this._sRVD;
            }
            private set
            {
                this._sRVD = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CaveFileData" /> class.</para>
        /// </summary>
        public CaveFileData()
        {
            this._sRVD = new System.Collections.ObjectModel.Collection<CaveFileDataSRVD>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileDataSRVD", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileDataSRVD
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("AZ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double AZ { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CL { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CM { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DT { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double DP { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DPI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float DPI { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("D", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double D { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("EXC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool EXC { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("EX", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EX { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FRID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int FRID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("INC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float INC { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("LT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double LT { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("L", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double L { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("LG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float LG { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("LK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool LK { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("LGT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double LGT { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("NM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NM { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PRTY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileDataSRVDPRTY PRTY { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("R", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double R { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("SC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SC { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("SH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileDataSRVDSH SH { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileDataSRVDTY TY { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("U", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double U { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileDataSRVDPRTY", Namespace="", AnonymousType=true)]
    public enum CaveFileDataSRVDPRTY
    {
        
        VERTICAL,
        
        HORIZONTAL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileDataSRVDSH", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileDataSRVDSH
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("HPRA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HPRA { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("HPRT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HPRT { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PRAZ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float PRAZ { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PRT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float PRT { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CaveFileDataSRVDSHRCRV> _rC;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("RC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RV", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CaveFileDataSRVDSHRCRV> RC
        {
            get
            {
                return this._rC;
            }
            private set
            {
                this._rC = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CaveFileDataSRVDSH" /> class.</para>
        /// </summary>
        public CaveFileDataSRVDSH()
        {
            this._rC = new System.Collections.ObjectModel.Collection<CaveFileDataSRVDSHRCRV>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileDataSRVDSHRC", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileDataSRVDSHRC
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CaveFileDataSRVDSHRCRV> _rV;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("RV", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CaveFileDataSRVDSHRCRV> RV
        {
            get
            {
                return this._rV;
            }
            private set
            {
                this._rV = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CaveFileDataSRVDSHRC" /> class.</para>
        /// </summary>
        public CaveFileDataSRVDSHRC()
        {
            this._rV = new System.Collections.ObjectModel.Collection<CaveFileDataSRVDSHRCRV>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileDataSRVDSHRCRV", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileDataSRVDSHRCRV
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Ag { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Lg { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Tc { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Tp { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileDataSRVDTY", Namespace="", AnonymousType=true)]
    public enum CaveFileDataSRVDTY
    {
        
        REAL,
        
        CLOSURE,
        
        VIRTUAL,
        
        START,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileUnit", Namespace="", AnonymousType=true)]
    public enum CaveFileUnit
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("m")]
        M,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileCartoPage", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileCartoPage
    {
        
        [System.Xml.Serialization.XmlElementAttribute("pageRectangles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CaveFileCartoPagePageRectangles PageRectangles { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileCartoPagePageRectangles", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileCartoPagePageRectangles
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("editable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Editable { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("layer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Layer Layer { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("style", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Style Style { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ZOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZOrder { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("endCorner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner EndCorner { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("interACorner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner InterACorner { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("interBCorner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner InterBCorner { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("startCorner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner StartCorner { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("bottomLeftGrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner BottomLeftGrip { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("bottomRightGrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner BottomRightGrip { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("centerGrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner CenterGrip { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paperType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaperType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("topLeftGrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner TopLeftGrip { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("topRightGrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Corner TopRightGrip { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CaveFileLayers", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CaveFileLayers
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Layer> _layerList;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("layerList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Layer> LayerList
        {
            get
            {
                return this._layerList;
            }
            private set
            {
                this._layerList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CaveFileLayers" /> class.</para>
        /// </summary>
        public CaveFileLayers()
        {
            this._layerList = new System.Collections.ObjectModel.Collection<Layer>();
        }
    }
}
